/**
 * Given an uid generate color in hexadecimal
 * @param {string} seed uid generated by firebase
 * @returns {string} color in hex format e.x. #ff0000
 */
export function generateColorBySeed (seed) {
  const hash = simpleHash(seed.toString())
  const hue = hash % 360
  const saturation = 70 + (hash % 30)
  const lightness = 40 + (hash % 20)
  return hslToHex(hue, saturation, lightness)
}

function simpleHash (str) {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  return Math.abs(hash)
}

function hslToHex (h, s, l) {
  l /= 100
  const a = s * Math.min(l, 1 - l) / 100
  const f = n => {
    const k = (n + h / 30) % 12
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1)
    return Math.round(255 * color).toString(16).padStart(2, '0')
  }
  return `#${f(0)}${f(8)}${f(4)}`
}
