/**
 * Extract dominant color from an image File using canvas sampling.
 * @param {File} file image file
 * @returns {Promise<string>} color in hex format e.g. #ff0000
 */
export function getDominantColor (file) {
  return new Promise((resolve) => {
    const img = new Image()
    const url = URL.createObjectURL(file)
    img.onload = () => {
      const SIZE = 50
      const canvas = document.createElement('canvas')
      canvas.width = SIZE
      canvas.height = SIZE
      const ctx = canvas.getContext('2d')
      ctx.drawImage(img, 0, 0, SIZE, SIZE)
      URL.revokeObjectURL(url)
      const { data } = ctx.getImageData(0, 0, SIZE, SIZE)
      let r = 0, g = 0, b = 0, count = 0
      for (let i = 0; i < data.length; i += 4) {
        if (data[i + 3] < 128) continue // skip transparent
        r += data[i]; g += data[i + 1]; b += data[i + 2]; count++
      }
      if (!count) { resolve(generateColorBySeed('fallback')); return }
      const avg = (v) => Math.round(v / count).toString(16).padStart(2, '0')
      resolve(`#${avg(r)}${avg(g)}${avg(b)}`)
    }
    img.onerror = () => { URL.revokeObjectURL(url); resolve(generateColorBySeed('fallback')) }
    img.src = url
  })
}

/**
 * Assign distinct colors to options. Options with an existing color (from image)
 * are kept as-is; the rest receive evenly-spaced hues avoiding the taken ones.
 * @param {Array<{id: string, color?: string}>} options
 * @returns {Array<{id: string, color: string}>}
 */
export function assignColors (options) {
  const takenHues = options
    .filter(o => o.color)
    .map(o => hexToHue(o.color))
    .filter(h => h !== null)

  const needColor = options.filter(o => !o.color)
  const count = needColor.length
  if (count === 0) return options

  // spread hues evenly, then shift away from taken ones
  const step = 360 / Math.max(count, 1)
  const assigned = needColor.map((o, i) => {
    let hue = (i * step + 30) % 360 // +30 offset to avoid red as first
    hue = shiftAwayFromTaken(hue, takenHues, step * 0.4)
    return { ...o, color: hslToHex(hue, 75, 48) }
  })

  const assignedMap = Object.fromEntries(assigned.map(o => [o.id, o.color]))
  return options.map(o => ({ ...o, color: o.color || assignedMap[o.id] }))
}

function shiftAwayFromTaken (hue, takenHues, minDist) {
  let shifted = hue
  for (const taken of takenHues) {
    const diff = Math.abs(((shifted - taken + 540) % 360) - 180)
    if (diff < minDist) shifted = (shifted + minDist - diff + 360) % 360
  }
  return shifted
}

function hexToHue (hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b)
  if (max === min) return null
  const d = max - min
  let h = max === r ? (g - b) / d + (g < b ? 6 : 0)
    : max === g ? (b - r) / d + 2
    : (r - g) / d + 4
  return (h / 6) * 360
}

/**
 * Given an uid generate color in hexadecimal
 * @param {string} seed uid generated by firebase
 * @returns {string} color in hex format e.x. #ff0000
 */
export function generateColorBySeed (seed) {
  const hash = simpleHash(seed.toString())
  const hue = hash % 360
  const saturation = 70 + (hash % 30)
  const lightness = 40 + (hash % 20)
  return hslToHex(hue, saturation, lightness)
}

function simpleHash (str) {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash
  }
  return Math.abs(hash)
}

function hslToHex (h, s, l) {
  l /= 100
  const a = s * Math.min(l, 1 - l) / 100
  const f = n => {
    const k = (n + h / 30) % 12
    const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1)
    return Math.round(255 * color).toString(16).padStart(2, '0')
  }
  return `#${f(0)}${f(8)}${f(4)}`
}
